// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbGoH22ss9nDz9J6VK6wvCDobAieYKAY',
    appId: '1:628545470546:web:f241e768b81b00d8c31f8b',
    messagingSenderId: '628545470546',
    projectId: 'fravarapp',
    authDomain: 'fravarapp.firebaseapp.com',
    databaseURL: 'https://fravarapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fravarapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpj3t0QNaKHPflUmLtaAGlMaRvD8OAZ54',
    appId: '1:628545470546:android:9573c2ac7c137081c31f8b',
    messagingSenderId: '628545470546',
    projectId: 'fravarapp',
    databaseURL: 'https://fravarapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fravarapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp2iYLZCJuItp-7tG9pHzIyjMyAotD2Zc',
    appId: '1:628545470546:ios:aa8c921988094b48c31f8b',
    messagingSenderId: '628545470546',
    projectId: 'fravarapp',
    databaseURL: 'https://fravarapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fravarapp.appspot.com',
    iosBundleId: 'com.example.fravarNfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp2iYLZCJuItp-7tG9pHzIyjMyAotD2Zc',
    appId: '1:628545470546:ios:405273e8ed80fa2dc31f8b',
    messagingSenderId: '628545470546',
    projectId: 'fravarapp',
    databaseURL: 'https://fravarapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fravarapp.appspot.com',
    iosBundleId: 'com.example.fravarNfc.RunnerTests',
  );
}
